### ISSUE TITLE
Project Outline - Features

### ISSUE THREAD

**Issue by r-spell** [taman7771/liftoff-assignments#1]
For the Features, try to give them more as a user story

you have "User login" what does user login give user's access to?

you have "Email confirmation", I might leave this for later because it might be a little complicated

you have  "Html Forms submission", what kinds of forms? why are they filling out forms? Do they sign up for an event using the form? Do they create an event using the form?

Try to think of your features as stories that help us understand what the app can do, from the overview it seems like maybe one could be 

"Users can check their kids in and out of day care via the app"

Let's look at your idea and try to think of features that are small and how you can build so that you have some things to show employers.

**Comment by taman7771** [comment]
outline updated per issues listed above
