### ISSUE TITLE
Project Outline - Technology

### ISSUE THREAD

**Issue by r-spell** [taman7771/liftoff-assignments#2]
For Technology/Learning try to include some more new things. 

If you want to have users login, then you might want to learn  `spring-filter-based-auth`

You might also want to use Bootstrap to make things look nice.  and some basic JavaScript or jQuery for some clickable features.  Let's look at ways to incorporate these as you restructure your project into manageable pieces.

**Comment by taman7771** [comment]
Outline updated for reported issues
