### ISSUE TITLE
Github Profile

### ISSUE THREAD

**Issue by r-spell** [taman7771/liftoff-assignments#3]
I like your bio, but you have "Spring", in your bio. I think you mean "SpringBoot". Also you might want to put a picture of yourself if you feel comfortable.

**Comment by taman7771** [comment]
The bio was full to it's cap. I couldn't add more words. But I removed hibernate and placed Spring Boot per your comment.

**Comment by taman7771** [comment]
I will look for good picture and place it in the profile.
